### PR TITLE
misc(docs): Improve the documentation on Description and Matcher

### PR DESCRIPTION
**Pull request by kevmoo**
Description: break out a single-sentence summary

Macher:
- break out a single-sentence summary for class and functions
- Append a note to the top of the functions that they are meant for
  subclasses, not end users – helpful in the 90% case of folks scanning
  the API docs

### CODE REVIEW

**Comment by kevmoo** [comment]
`CustomMatcher` docs before:

screen shot 2018-06-14 at 11 21 58 am

After

screen shot 2018-06-14 at 11 22 12 am

**Comment by kevmoo** [comment]
or @jakemac53 – if you're bored

**Comment by natebosch** [comment]
I'm not sure I agree that should be the first sentence...

**Comment by kevmoo** [comment]
> I'm not sure I agree that should be the first sentence...

I can back that out. Pretty easy. Maybe we need an annotation that is `only for subclasses/infra` or something...

**Comment by kevmoo** [comment]
PTAL

**Pull request merged**
