### PR TITLE
Allow null-safe code to do `same(null)`.

### PR DESCRIPTION
**Pull request by stereotype441**

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
CC @natebosch – wait for his approval!

**Comment by natebosch** [comment]
Either `isNull` or `equals(null)` should cover this. There is no value equal to `null` that isn't also identical right?

What use case needs this?

**Comment by stereotype441** [comment]
> Either `isNull` or `equals(null)` should cover this. There is no value equal to `null` that isn't also identical right?
> 
> What use case needs this?

My particular use case looks roughly like this:

```dart
...set up some state...
var nodeInfoBeforeChanges = getNodeInfo(...);
...take some additional actions...
// Verify that the node info was unchanged by these actions
expect(getNodeInfo(...), same(nodeInfoBeforeChanges));
```

I don't want the test to be sensitive to whether or not the node info is null.  I just want it to make sure that the new value is identical to the old value.

Granted, I can rewrite my code to do the test some other way, but it seems silly to prohibit people from passing `null` to `same` when it used to work just fine (before null safety) and there's no real null safety benefit gained by prohibiting it.

Besides, we have to make some change, because the current behavior is really bad: in sound null checking mode, `same(null)` is accepted statically but fails at runtime.  I don't see any downside to restoring the functionality we used to have.

**Comment by kevmoo** [comment]
This seems like a regression and existing behavior right? If so, let's go
with Paul's change. At least in my opinion. Please add a test for this case
though

**Comment by natebosch** [comment]
> This seems like a regression and existing behavior right?

I don't know that it is. Unsound null safety is not impacted.

I can see an argument at least that it shouldn't be necessary to use `!` just to get around a nullable your in a test, but I'm not entirely sure.

> it seems silly to prohibit people from passing `null` to `same` when it used to work just fine (before null safety)

This isn't the only place that we disallow null starting with null safety and were still backwards compatible with existing unmigrated code.



> there's no real null safety benefit gained by prohibiting it.

For me the argument is more about what kind of test design we encourage. I'm still having a hard time convincing myself one way or the other whether it's OK to have a test that you write, where at the time of the test you don't know whether a given value should be null or non-null... Maybe you can send me some links to the code here or off thread so I can get a more complete picture of why we don't know in advance where to look for null or or non-null identical object.

**Comment by stereotype441** [comment]
Hmm, looks like I opened a much larger can of worms than I intended to.  I thought I had simply discovered a small error in the migration of the matcher package, and figured I would save folks some time by submitting a PR to add the missing `?`.  But it looks like it's turning into a wider design discussion about what the API for the matcher package should be, and I don't really have an axe to grind about that.  So I'm going to go ahead and close my PR and let the two of you sort out what solution you feel is best.  If you decide you want to go with the solution I proposed it should be easy enough to replicate my one-character change 😃

Nate, you asked to see my code in context.  You can find it here: https://dart-review.googlesource.com/c/sdk/+/175500/4/pkg/_fe_analyzer_shared/test/flow_analysis/flow_analysis_test.dart#2388.  Please be gentle--this is work in progress code that's not yet ready for code review.

**Comment by natebosch** [comment]
I discussed this with @grouma and @jakemac53 and we do think it's worth changing this.

**Review by natebosch — APPROVED** [review]

**Pull request merged**
