### PR TITLE
add DateTime isCloseTo matcher

### PR DESCRIPTION
**Pull request by boumenot**

### CODE REVIEW

**Comment by boumenot** [comment]
Any interest in a matcher for DateTime?

**Comment by natebosch** [comment]
I don't have strong opinions on whether this is useful enough to include here.

One concern I have - is the name clear and discoverable enough? Will it be obvious that this relates to `DateTime`?

@kevmoo - any thoughts on whether this is worth including?

**Comment by kevmoo** [comment]
Not a big fan.

We already have `closeTo` – so adding `isCloseTo` will just be confusing.

We *could** change `closeTo` to take `dynamic, dynamic` and support `num, num` OR `DateTime, Duration` – but...ugh...

**Comment by natebosch** [comment]
`temporallyNear`?

**Comment by boumenot** [comment]
I am not tied to the name, and I am fine with any choice.

I picked the name isCloseTo based on the [FluentAssertions](https://fluentassertions.com/).  (But, after reading the style guide closeTo is a better choice.)  [Shouldly](https://github.com/shouldly/shouldly) appears to just use `.ShouldBe`, which is more inline with the closeTo option. [Truth](https://google.github.io/truth/)'s assertions do not appear to map very well, so it is hard to find inspiration.  I checked a few other _fluent assertion_ libraries, and they did not have this style of assertion.

Scala's [FlatSpec](http://doc.scalatest.org/3.0.1/#org.scalatest.FlatSpec) had an interesting take, but I am not sure if this translates very well to Dart.

```scala
actual shouldBe (expected +- tolerance)
```

More ideas for the mix:

 1. about()
 1. around()
 1. circa()

I think temporallyNear is descriptive, but not as pithy as I was wanted. 😄

**Pull request closed without merging**
